spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa
    username: jpa
    password: jpa
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
